CinemaSystemWebapp/Models/Category.cs
using System;
using System.Collections.Generic;

namespace CinemaSystemWebapp.Models
{
    public partial class Category
    {
        public Category()
        {
            Films = new HashSet<Film>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Desc { get; set; } = null!;

        public virtual ICollection<Film> Films { get; set; }
    }
}

CinemaSystemWebapp/Controllers/CategoryController.cs
using CinemaSystemWebapp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaSystemWebapp.Controllers
{
    public class CategoryController : Controller
    {

        public CinemaSystemContext dbcontext { get; set; } = new();

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            dbcontext.Dispose();
        }

        public IActionResult Index(int id)
        {
            return View(dbcontext.Categories.Include(e => e.Films).FirstOrDefault(e => e.Id == id));
        }
    }
}

CinemaSystemWebapp/Controllers/FilmController.cs
using CinemaSystemWebapp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaSystemWebapp.Controllers
{
    public class FilmController : Controller
    {
        public CinemaSystemContext dbcontext { get; set; } = new();

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            dbcontext.Dispose();
        }

        public IActionResult Index(int id, string? message)
        {
            ViewBag.Message = message;
            ViewBag.Rooms = dbcontext.Rooms.ToList();
            return View(
                dbcontext.Films
                .Include(e => e.Categories)
                .Include(e => e.Shows)
                .ThenInclude(e => e.Room)
                .FirstOrDefault(e => e.Id == id)
            );
        }
    }
}

CinemaSystemWebapp/Views/Category/Index.cshtml
@model Category

@{
    ViewData["Title"] = Model.Name;
}

<div class="container mt-3">
    <h1 class="text-center text-white">@Model.Name</h1>

    <p class="text-muted">@Model.Desc</p>

    <hr>

    <div class="hanime-body__cards container-fluid">
        <div class="row">
            @foreach (var film in Model.Films)
            {
                <a asp-controller="Film" asp-action="Index" asp-route-id="@film.Id" class="hanime-body__card-item col-xl-3 col-md-4 col-sm-6 col-xs-12">
                    <img class="hanime-body__card-item--thumbnail" style="object-position: center; object-fit: cover;" height="200"
                     src="@film.ImageUrl">
                    <div class="hanime-body__card-item--body">
                        <p class="hanime-body__card-item--body--title">@film.Name</p>
                        <p class="hanime-body__card-item--body--sub">@film.ReleaseDate</p>
                    </div>
                </a>
            }
        </div>
    </div>
</div>